---
name: Terraform Validate

"on":
  pull_request:
    paths:
      - "infra/**"

permissions:
  contents: read

jobs:
  tf-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    timeout-minutes: 3

    env:
      TF_VAR_github_org: ${{ secrets.TF_TEST_GITHUB_ORG }}
      GITHUB_TOKEN: ${{ secrets.TF_TEST_GITHUB_TOKEN }}
      TF_CLI_ARGS: "-no-color"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3.1.2
        with:
          terraform_version: "~> 1.0"

      - name: Terraform fmt check
        run: terraform fmt -check -recursive -no-color .
        working-directory: infra

      - name: Terraform init
        run: terraform init -backend=false -no-color -input=false
        working-directory: infra

      - name: Terraform validate
        run: terraform validate -no-color
        working-directory: infra

      - name: Terraform plan
        run: terraform plan -input=false -no-color
        working-directory: infra
